name: 'gluten_free_flour'
post_ids: [
  '8bnn0y',
  '88oj1c',
  'hrdobw',
  '6jk5gc',
  '1rz9xu',
  '2fr0vn',
  'e2ilvb',
  '7s9440',
  '769uw0'
  ]
brands: [
  'King Arthur',
  'Cup4cup',
  "Bob's Red Mill"
  ]
