name: product-meta-analysis
dependencies:
  - python>=3.8
  - pandas
  - numpy
  - pip
  - pip:
    - requests
    - beautifulsoup4
    - pytest
    - pyyaml
    - nltk
    - jupyter
    - ipykernel
    - matplotlib
    - statsmodels
